import '../assets/js/common.js'
import '../assets/scss/common.scss'
import './pages/index/index'
import './pages/index/index.scss'
import './components/header/header'
import './components/header/header.scss'
